<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2JQxXk3\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2JQxXk3/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container2JQxXk3.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container2JQxXk3\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container2JQxXk3\appAppKernelProdContainer([
    'container.build_hash' => '2JQxXk3',
    'container.build_id' => '4cd2cfa6',
    'container.build_time' => 1710179165,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2JQxXk3');
